import type { PlatformPluginDef } from './types';

/**
 * Every plugin the VaakuOS tenant app currently names — including ones that
 * only exist as frontend cards / provider slugs until they are seeded into
 * `/integration-catalog`. Offering, status and incidents are controllable
 * only after a catalog row exists.
 */
export const PLATFORM_PLUGINS: PlatformPluginDef[] = [
  {
    provider: 'google_sheets',
    name: 'Google Sheets',
    description: 'Import and export contacts against a connected spreadsheet.',
    category: 'productivity',
    implementation: 'wired',
  },
  {
    provider: 'shopify',
    name: 'Shopify',
    description: 'Orders, checkouts and abandoned carts from a Shopify store.',
    category: 'ecommerce',
    implementation: 'wired',
  },
  {
    provider: 'woocommerce',
    name: 'WooCommerce',
    description: 'Cart and order events from a WooCommerce storefront.',
    category: 'ecommerce',
    implementation: 'wired',
  },
  {
    provider: 'facebook_leads',
    name: 'Facebook Lead Ads',
    description: 'Pull Meta lead-ad form submissions into contacts.',
    category: 'social',
    implementation: 'wired',
  },
  {
    provider: 'custom_website',
    name: 'Custom website',
    description: 'Storefront SDK snippet for carts, identity and orders.',
    category: 'ecommerce',
    implementation: 'wired',
  },
  {
    provider: 'wix',
    name: 'Wix',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'ecommerce',
    implementation: 'frontend_only',
  },
  {
    provider: 'magento',
    name: 'Magento',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'ecommerce',
    implementation: 'frontend_only',
  },
  {
    provider: 'bigcommerce',
    name: 'BigCommerce',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'ecommerce',
    implementation: 'frontend_only',
  },
  {
    provider: 'amazon',
    name: 'Amazon',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'ecommerce',
    implementation: 'frontend_only',
  },
  {
    provider: 'hubspot',
    name: 'HubSpot',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'other',
    implementation: 'frontend_only',
  },
  {
    provider: 'salesforce',
    name: 'Salesforce',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'other',
    implementation: 'frontend_only',
  },
  {
    provider: 'zoho',
    name: 'Zoho CRM',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'other',
    implementation: 'frontend_only',
  },
  {
    provider: 'pipedrive',
    name: 'Pipedrive',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'other',
    implementation: 'frontend_only',
  },
  {
    provider: 'telegram',
    name: 'Telegram',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'messaging',
    implementation: 'frontend_only',
  },
  {
    provider: 'messenger',
    name: 'Messenger',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'messaging',
    implementation: 'frontend_only',
  },
  {
    provider: 'instagram',
    name: 'Instagram',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'social',
    implementation: 'frontend_only',
  },
  {
    provider: 'slack',
    name: 'Slack',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'messaging',
    implementation: 'frontend_only',
  },
  {
    provider: 'twilio',
    name: 'Twilio',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'messaging',
    implementation: 'frontend_only',
  },
  {
    provider: 'razorpay',
    name: 'Razorpay',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'other',
    implementation: 'frontend_only',
  },
  {
    provider: 'stripe',
    name: 'Stripe',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'other',
    implementation: 'frontend_only',
  },
  {
    provider: 'paypal',
    name: 'PayPal',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'other',
    implementation: 'frontend_only',
  },
  {
    provider: 'google_analytics',
    name: 'Google Analytics',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'developer',
    implementation: 'frontend_only',
  },
  {
    provider: 'mixpanel',
    name: 'Mixpanel',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'developer',
    implementation: 'frontend_only',
  },
  {
    provider: 'segment',
    name: 'Segment',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'developer',
    implementation: 'frontend_only',
  },
  {
    provider: 'amplitude',
    name: 'Amplitude',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'developer',
    implementation: 'frontend_only',
  },
  {
    provider: 'notion',
    name: 'Notion',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'productivity',
    implementation: 'frontend_only',
  },
  {
    provider: 'airtable',
    name: 'Airtable',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'productivity',
    implementation: 'frontend_only',
  },
  {
    provider: 'gmail',
    name: 'Gmail',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'productivity',
    implementation: 'frontend_only',
  },
  {
    provider: 'calendar',
    name: 'Google Calendar',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'productivity',
    implementation: 'frontend_only',
  },
  {
    provider: 'drive',
    name: 'Google Drive',
    description: 'Declared in the tenant plugins list; not seeded or wired yet.',
    category: 'productivity',
    implementation: 'frontend_only',
  },
  {
    provider: 'zapier',
    name: 'Zapier',
    description: 'Named on the product roadmap; not declared in the tenant app yet.',
    category: 'automation',
    implementation: 'frontend_only',
  },
  {
    provider: 'make',
    name: 'Make',
    description: 'Named on the product roadmap; not declared in the tenant app yet.',
    category: 'automation',
    implementation: 'frontend_only',
  },
];

export const PLATFORM_PLUGIN_BY_PROVIDER = Object.fromEntries(
  PLATFORM_PLUGINS.map((p) => [p.provider, p]),
) as Record<string, PlatformPluginDef>;
