import { ModuleConfig } from "@/types/admin.types";
import { Permission } from "@/types/permissions.enum";

export const INTERNAL_MODULES: ModuleConfig[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/dashboard",
    icon: "Squares2X2Icon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.OWNER_DASHBOARD_READ],
  },
  {
    id: "team",
    name: "Team",
    path: "/team",
    icon: "UsersIcon",
    adminTypes: ["owner"],
    requiredPermissions: [




      Permission.USERS_READ,
      Permission.USERS_CREATE,
      Permission.USERS_UPDATE,
      Permission.USERS_DELETE,
      Permission.USERS_MANAGE,
      Permission.ROLES_READ,
      Permission.ROLES_CREATE,
      Permission.ROLES_UPDATE,
      Permission.ROLES_DELETE,
      Permission.ROLES_MANAGE,
    ],
    children: [
      {
        id: "users",
        name: "Users",
        path: "/team/user",
        icon: "UserIcon",
        adminTypes: ["owner"],
        requiredPermissions: [




          Permission.USERS_READ,
          Permission.USERS_CREATE,
          Permission.USERS_UPDATE,
          Permission.USERS_DELETE,
          Permission.USERS_MANAGE,
        ],
      },
      {
        id: "roles",
        name: "Roles",
        path: "/team/role",
        icon: "ShieldCheckIcon",
        adminTypes: ["owner"],
        requiredPermissions: [
          Permission.ROLES_READ,
          Permission.ROLES_CREATE,
          Permission.ROLES_UPDATE,
          Permission.ROLES_DELETE,
          Permission.ROLES_MANAGE,
        ],
      },
    ],
  },
  {
    id: "agencies",
    name: "Agencies",
    path: "/agencies",
    icon: "BriefcaseIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.AGENCIES_READ,
      Permission.AGENCIES_CREATE,
      Permission.AGENCIES_UPDATE,
      Permission.AGENCIES_DELETE,
      Permission.AGENCIES_LOGIN_AS,
    ],
  },
  {
    id: "brands",
    name: "Brands",
    path: "/brands",
    icon: "BuildingOfficeIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.BRANDS_READ,
      Permission.BRANDS_CREATE,
      Permission.BRANDS_UPDATE,
      Permission.BRANDS_DELETE,
      Permission.BRANDS_LOGIN_AS,
    ],
  },
  {
    id: "billing",
    name: "Billing",
    path: "/billing",
    icon: "CreditCardIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.OWNER_BILLING_READ,
      Permission.OWNER_BILLING_MANAGE,
      Permission.COUPONS_READ,
      Permission.COUPONS_CREATE,
      Permission.COUPONS_UPDATE,
      Permission.COUPONS_DELETE,
    ],
  },
  {
    id: "subscription",
    name: "Subscription",
    path: "/subscription",
    icon: "CalendarIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.PLANS_MANAGE,
      Permission.SUBSCRIPTIONS_READ,
      Permission.FEATURES_MANAGE,
    ],
  },
  {
    id: "coupon",
    name: "Coupon",
    path: "/coupon",
    icon: "TicketIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.COUPONS_READ,
      Permission.COUPONS_CREATE,
      Permission.COUPONS_UPDATE,
      Permission.COUPONS_DELETE,
    ],
  },
  {
    id: "offer",
    name: "Offers",
    path: "/offer",
    icon: "TagIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.OFFERS_READ,
      Permission.OFFERS_CREATE,
      Permission.OFFERS_UPDATE,
      Permission.OFFERS_DELETE,
    ],
  },
  {
    id: "faq",
    name: "FAQ",
    path: "/faq",
    icon: "QuestionMarkCircleIcon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.MASTER_DATA_MANAGE],
  },
  {
    id: "master",
    name: "Master Data",
    path: "/master",
    icon: "ServerIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.MASTER_DATA_READ,
      Permission.MASTER_DATA_MANAGE,
      Permission.INTEGRATIONS_READ,
      Permission.INTEGRATIONS_MANAGE,
    ],
    children: [
      {
        id: "plan-features",
        name: "Plan Features",
        path: "/master/plan-features",
        icon: "BoltIcon",
        adminTypes: ["owner"],
        requiredPermissions: [Permission.FEATURES_MANAGE],
      },
      {
        id: "faq-categories",
        name: "FAQ Categories",
        path: "/master/faq-categories",
        icon: "QuestionMarkCircleIcon",
        adminTypes: ["owner"],
        requiredPermissions: [Permission.MASTER_DATA_MANAGE],
      },
      {
        id: "integrations",
        name: "Integrations",
        path: "/master/integrations",
        icon: "ArrowsRightLeftIcon",
        adminTypes: ["owner"],
        requiredPermissions: [
          Permission.INTEGRATIONS_READ,
          Permission.INTEGRATIONS_MANAGE,
        ],
      },
    ],
  },
  {
    id: "features",
    name: "Features",
    path: "/features",
    icon: "BoltIcon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.FEATURES_MANAGE],
  },
  {
    id: "monitoring",
    name: "Monitoring",
    path: "/monitoring",
    icon: "ChartBarIcon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.MONITORING_READ],
  },
  {
    id: "audit-logs",
    name: "Audit Trail",
    path: "/audit-logs",
    icon: "DocumentTextIcon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.AUDIT_LOGS_READ],
  },
  {
    id: "error-logs",
    name: "Error Logs",
    path: "/error-logs",
    icon: "ExclamationCircleIcon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.AUDIT_LOGS_READ],
  },
  {
    id: "config",
    name: "Config",
    path: "/config",
    icon: "Cog6ToothIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.CONFIG_READ,
      Permission.CONFIG_UPDATE,
    ],
  },
  {
    id: "emergency",
    name: "Emergency",
    path: "/emergency",
    icon: "ExclamationTriangleIcon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.EMERGENCY_MANAGE],
  },
  {
    id: "templates",
    name: "Templates",
    path: "/templates",
    icon: "RectangleGroupIcon",
    adminTypes: ["owner"],
    requiredPermissions: [
      Permission.TEMPLATES_READ,
      Permission.TEMPLATES_CREATE,
      Permission.TEMPLATES_UPDATE,
      Permission.TEMPLATES_DELETE,
      Permission.TEMPLATES_APPROVE,
    ],
  },
  {
    id: "blog",
    name: "Blog",
    path: "/blog",
    icon: "NewspaperIcon",
    adminTypes: ["owner"],
    requiredPermissions: [Permission.MASTER_DATA_MANAGE],
    children: [
      {
        id: "all-blogs",
        name: "All Blogs",
        path: "/blog",
        icon: "DocumentTextIcon",
        adminTypes: ["owner"],
        requiredPermissions: [Permission.MASTER_DATA_MANAGE],
      },
      {
        id: "blog-categories",
        name: "Categories",
        path: "/blog/categories",
        icon: "TagIcon",
        adminTypes: ["owner"],
        requiredPermissions: [Permission.MASTER_DATA_MANAGE],
      },
    ],
  },
];
